name: Мой первый CI пайплайн

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Устанавливаем Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Устанавливаем зависимости
        run: |
          pip install flask pytest
      
      - name: Запускаем тесты
        run: |
          python -m pytest test_app.py -v
      
      - name: Успех!
        run: echo "✅ Все тесты прошли!"
